<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>
  <ItemGroup>
    <Compile Include="../../src/HaloPixelToolBox/Services/Audio/WindowsAudioEndpointService.cs" Link="WindowsAudioEndpointService.cs" />
    <Compile Include="../../src/HaloPixelToolBox/Models/AudioControlModels.cs" Link="AudioControlModels.cs" />
  </ItemGroup>
</Project>
